# Generated by Django 4.0.5 on 2022-06-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_auto_20200307_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='follower_user',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='following_user',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
