# Generated by Django 4.0.5 on 2022-06-06 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0005_remove_like_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='image_id',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='user_id',
            new_name='user',
        ),
    ]
